### PR TITLE
Add prototypes flag to warnings CI

### PR DESCRIPTION
**Pull request by lpsaavedra**
### Description

Add prototypes compilation to ensure that they are all up to date.  Follow up on PR #1249.

### Checklist (will be removed when merged)
See [this page](https://chaos-polymtl.github.io/lethe/documentation/contributing.html#pull-requests) for more information about the pull request process.

Code related list:
- [x] The branch is rebased onto master

Pull request related list:
- [x] Labels are applied
- [x] There are at least 2 reviewers (or 1 if small feature) excluding the responsible for the merge
- [x] The PR description is cleaned and ready for merge

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Comment by blaisb** [comment]
Are you sure you want to compile the prototype for all CI instances? I don't mind that, but it seems like a lot of extra compilation on all instances. :)

In all cases, I have rebased your branch

**Comment by lpsaavedra** [comment]
Well now that you say it... it might be a bit too much, so we can leave them only in the warnings CI. I think it will help us to avoid having broken prototypes at some point

**Comment by lpsaavedra** [comment]
It seems that we cannot support both 9.5 and master version of deal.II... do we want to switch to 9.6 some time soon?

**Comment by blaisb** [comment]
@lpsaavedra see #1251 . Once it is merged we can rebase and try again this branch.

**Comment by blaisb** [comment]
@lpsaavedra you just need to rebase and we should be good

**Comment by lpsaavedra** [comment]
Okay, it seems to be good to go now :)

**Pull request merged**
