### PR TITLE
Checkpointing current_file_id for file insertion

### PR DESCRIPTION
**Pull request by OGaboriault**
### Description

The current_file_id wasn't being checkpointed. This means that the next file being used to insert particles would be the first one after a restart. 

### Solution

current_file_id is now being checkpointed.

### Testing

Haven`t been tested yet, but I don`t think it need to be. Logically, it should work. 

### Documentation

N/A

### Miscellaneous (will be removed when merged)

N/A

### Checklist (will be removed when merged)
See [this page](https://chaos-polymtl.github.io/lethe/documentation/contributing.html#pull-requests) for more information about the pull request process.

Code related list:
- [X] All in-code documentation related to this PR is up to date (Doxygen format)
- [X] Lethe documentation is up to date
- [x] Fix has unit test(s) (preferred) or application test(s)
- [X] The branch is rebased onto master
- [X] Changelog (CHANGELOG.md) is up to date
- [X] Code is indented with indent-all and .prm files (examples and tests) with prm-indent

Pull request related list:
- [X] Labels are applied
- [X] There are at least 2 reviewers (or 1 if small feature) excluding the responsible for the merge
- [X] If this PR closes an issue or is related to a project, it is linked in the "Projects" or "Development" section
- [X] If the fix is temporary, an issue is opened
- [X] The PR description is cleaned and ready for merge

### CODE REVIEW

**Comment by acdaigneault** [comment]
You said no need to test it, but did ou make sure it works? Like, you tried a restart? 
I know it might be a like specific, but I would add a test. If somehow something else broke that feature, will would be a painfull to debug. Failling restarts are hard to debug as we have seen lately. :)

**Comment by blaisb** [comment]
I think I agree with @acdaigneault I would prefer if you could add a test here. Does not have to be complicated, but it will be impossible to verify that this feature still works correctly
TBH, we have added a lot of restart tests lately, but we need even more

**Comment by OGaboriault** [comment]
I'll do a test tonight or tomorrow

**Review by acdaigneault — COMMENTED** [review]
Tell me when it is ready for final review :) (re-request the review)

**Review by acdaigneault — APPROVED** [review]
Thanks for the tesstttt

**Review by blaisb — APPROVED** [review]

**Pull request merged**
