### PR TITLE
Remove gifs from repo

### PR DESCRIPTION
**Pull request by hepap**
### Description

Gifs in the documentation were taking too much space. They were replace by embed youtube video.

### Checklist (will be removed when merged)
See [this page](https://chaos-polymtl.github.io/lethe/documentation/contributing.html#pull-requests) for more information about the pull request process.

Code related list:
- [x] All in-code documentation related to this PR is up to date (Doxygen format)
- [x] Lethe documentation is up to date
- [ ] The branch is rebased onto master
- [x] Code is indented with indent-all and .prm files (examples and tests) with prm-indent

Pull request related list:
- [x] Labels are applied
- [x] There are at least 2 reviewers (or 1 if small feature) excluding the responsible for the merge
- [x] If this PR closes an issue or is related to a project, it is linked in the "Projects" or "Development" section
- [x] If any future works is planed, an issue is opened
- [ ] The PR description is cleaned and ready for merge

### CODE REVIEW

**Review by AmishgaAlphonius — COMMENTED** [review]
Nice work, I only have a few comments :)

**Review by blaisb — APPROVED** [review]
Good from my side. Just ping me when it's ready to be merged.

**Review by AmishgaAlphonius — APPROVED** [review]

**Comment by blaisb** [comment]
@hepap can you rebase the changelog then I can merge?

**Comment by hepap** [comment]
@blaisb done :)

**Pull request merged**
